language: java
jdk:
- oraclejdk8
env:
  global:
    - MAVEN_OPTS="-Dmaven.artifact.threads=64 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
cache:
  directories:
  - "$HOME/.m2"
install: mvn clean install -DskipTests -Dinvoker.skip=true --batch-mode
script: mvn clean install -e --batch-mode
